### ISSUE TITLE
Exception with partial content (206)

### ISSUE THREAD

**Issue by lmivan** [andrewgaul/s3proxy#63]
I try to serve .mp4 files, so I put an nginx in front of s3proxy to set the right `content-type` (video/mp4). Once I do this I can write the following url in the browser: http://localhost/6015_2018_2035.h264.cutted.mp4

If I don't set the `content-type` the video is downloaded instead of being reproduced in the browser (chrome in my case).

The problem is that when chrome tries to reproduce the video it sends two connections. The second one responds with a 206 (partial content) and with the right header (byte ranges) but at the end I get the following exception:

```
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{WRITING}:IDLE-->WRITING
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 32768 SelectChannelEndPoint@4465ed37{/127.0.0.1:48839<->9090,Open,in,out,-,W,1/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{IDLE}:WRITING-->IDLE
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@56cd6ef[PROCESSING][i=null,cb=Blocker@69df07da{null}] generate: DONE (null,[p=32768,l=32768,c=32768,r=0],false)@COMMITTED
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@56cd6ef[PROCESSING][i=null,cb=Blocker@69df07da{null}] generate: FLUSH (null,[p=0,l=32768,c=32768,r=32768],false)@COMMITTED
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@18916c5b{IDLE} [HeapByteBuffer@3fb28ad9[p=0,l=32768,c=32768,r=32768]={<<<\x1d\x88\x11x6=\xA4\\QR\xF7Z\xD5\xFa\xB2\x90\x94...\x8b}\x1b@\xD7\x8bF\xAb\xCb\x12\xEd\x85\x06t\x0f>>>}]
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{WRITING}:IDLE-->WRITING
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 32768 SelectChannelEndPoint@4465ed37{/127.0.0.1:48839<->9090,Open,in,out,-,W,0/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{IDLE}:WRITING-->IDLE
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@56cd6ef[PROCESSING][i=null,cb=Blocker@69df07da{null}] generate: DONE (null,[p=32768,l=32768,c=32768,r=0],false)@COMMITTED
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@56cd6ef[PROCESSING][i=null,cb=Blocker@69df07da{null}] generate: FLUSH (null,[p=0,l=32768,c=32768,r=32768],false)@COMMITTED
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@18916c5b{IDLE} [HeapByteBuffer@3fb28ad9[p=0,l=32768,c=32768,r=32768]={<<<\x17\x88\x8eC\xA4C\xC5\x85\xB3\x88\x1a\xA5\xB4\xDft0\xAb...\xDd\xA5\xFd\xC1\xC9\xEb\x0b\xD7\xB9\x0f\xF3\xD329I>>>}]
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{WRITING}:IDLE-->WRITING
15:26:13.819 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 32768 SelectChannelEndPoint@4465ed37{/127.0.0.1:48839<->9090,Open,in,out,-,W,0/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:13.820 [qtp2032647583-21 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@18916c5b{IDLE}:WRITING-->IDLE

...
... more than 4000 lines with the same trace
...

15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@1703ec5e{IDLE} [HeapByteBuffer@3fb28ad9[p=0,l=32768,c=32768,r=32768]={<<<T\xEe\x07T\xE9e\x8e\xBce\x0f\x18Oa~\xBa}\xB1...\xEa\xFb\x08\xF3e\xE1ydDe?\xC9\x04\xF4\xD6>>>}]
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{WRITING}:IDLE-->WRITING
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 32768 SelectChannelEndPoint@4d0efa12{/127.0.0.1:48843<->9090,Open,in,out,-,W,0/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{IDLE}:WRITING-->IDLE
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@60b9d7b1[PROCESSING][i=null,cb=Blocker@35eea7f5{null}] generate: DONE (null,[p=32768,l=32768,c=32768,r=0],false)@COMMITTED
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@60b9d7b1[PROCESSING][i=null,cb=Blocker@35eea7f5{null}] generate: FLUSH (null,[p=0,l=32768,c=32768,r=32768],false)@COMMITTED
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@1703ec5e{IDLE} [HeapByteBuffer@3fb28ad9[p=0,l=32768,c=32768,r=32768]={<<<JI\x87\x1a\xF5\xDa8\xD5e\xF0\xEem\xFd\xC12\xEc...\x9b\xEf\xA9H\xF6\xD6*\xB0~\xD7R]1-\x1b>>>}]
15:26:14.851 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{WRITING}:IDLE-->WRITING
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write exception
org.eclipse.jetty.io.EofException: null
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:355) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at com.google.common.io.ByteStreams.copy(ByteStreams.java:179) [guava-16.0.1.jar:na]
    at org.gaul.s3proxy.S3ProxyHandler.handleGetBlob(S3ProxyHandler.java:979) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:392) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:201) [classes/:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45-internal]
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    ... 24 common frames omitted
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{IDLE}:WRITING-->IDLE
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@60b9d7b1[PROCESSING][i=null,cb=Blocker@35eea7f5{null}] generate: FLUSH (null,[p=0,l=32768,c=32768,r=32768],true)@COMPLETING
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@1703ec5e{IDLE} [HeapByteBuffer@3fb28ad9[p=0,l=32768,c=32768,r=32768]={<<<JI\x87\x1a\xF5\xDa8\xD5e\xF0\xEem\xFd\xC12\xEc...\x9b\xEf\xA9H\xF6\xD6*\xB0~\xD7R]1-\x1b>>>}]
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{WRITING}:IDLE-->WRITING
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - write exception
org.eclipse.jetty.io.EofException: null
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:171) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.gaul.s3proxy.S3ProxyHandler.handleGetBlob(S3ProxyHandler.java:981) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:392) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:201) [classes/:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45-internal]
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    ... 23 common frames omitted
15:26:14.853 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@1703ec5e{IDLE}:WRITING-->IDLE
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.server.HttpOutput - 
org.eclipse.jetty.io.EofException: null
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:171) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.gaul.s3proxy.S3ProxyHandler.handleGetBlob(S3ProxyHandler.java:981) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:392) [classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:201) [classes/:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45-internal]
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    ... 23 common frames omitted
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.eclipse.jetty.io.AbstractEndPoint - onClose SelectChannelEndPoint@4d0efa12{/127.0.0.1:48843<->9090,CLOSED,in,out,-,-,3/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.ChannelEndPoint - close SelectChannelEndPoint@4d0efa12{/127.0.0.1:48843<->9090,CLOSED,in,out,-,-,3/30000,HttpConnection}{io=0,kio=0,kro=1}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.io.SelectorManager - Destroyed SelectChannelEndPoint@4d0efa12{/127.0.0.1:48843<->9090,CLOSED,ISHUT,OSHUT,-,-,3/30000,HttpConnection}{io=0,kio=-1,kro=-1}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.io.AbstractConnection - onClose HttpConnection@711dd5b5{FILLING}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.eclipse.jetty.io.AbstractEndPoint - onClose SelectChannelEndPoint@4d0efa12{/127.0.0.1:48843<->9090,CLOSED,ISHUT,OSHUT,-,-,3/30000,HttpConnection}{io=0,kio=-1,kro=-1}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.server.HttpChannel - 
org.eclipse.jetty.io.EofException: null
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) ~[jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:355) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at com.google.common.io.ByteStreams.copy(ByteStreams.java:179) ~[guava-16.0.1.jar:na]
    at org.gaul.s3proxy.S3ProxyHandler.handleGetBlob(S3ProxyHandler.java:979) ~[classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:392) ~[classes/:na]
    at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:201) ~[classes/:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45-internal]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45-internal]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45-internal]
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170) ~[jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    ... 24 common frames omitted
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG o.e.jetty.server.HttpChannelState - HttpChannelState@50db53b7{s=DISPATCHED i=true a=null} unhandle DISPATCHED
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.http.HttpParser - close HttpParser{s=END,0 of 0}
15:26:14.854 [qtp2032647583-18 - /videos/6015_2018_2035.h264.cutted.mp4] DEBUG org.eclipse.jetty.http.HttpParser - END --> CLOSED
15:26:14.854 [qtp2032647583-18] DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@3f99f0a6{r=1,c=false,a=IDLE,uri=-} handle exit, result COMPLETE
15:26:14.854 [qtp2032647583-18] DEBUG org.eclipse.jetty.http.HttpParser - atEOF HttpParser{s=CLOSED,0 of 0}
15:26:14.854 [qtp2032647583-18] DEBUG org.eclipse.jetty.http.HttpParser - parseNext s=CLOSED HeapByteBuffer@40635532[p=0,l=0,c=0,r=0]={<<<>>>}
15:26:14.854 [qtp2032647583-18] DEBUG o.e.jetty.io.AbstractConnection - FILLING-->IDLE HttpConnection@711dd5b5{IDLE}
```

**Comment by kahing** [comment]
could you share your nginx config? What's s3proxy talking to in the backend?

**Comment by andrewgaul** [comment]
Does the client request actually fail or does S3Proxy just log the EOFException?  Could you minimize this test case a little more with curl or similar request?

**Comment by andrewgaul** [comment]
Could you enable trace-level logging via:

```
java -DLOG_LEVEL=trace -jar s3proxy
```

**Comment by lmivan** [comment]
My nginx configuration file:

```
server {
    listen 80 default_server;

    client_max_body_size    800m;

    server_name localhost;

    location / {
        proxy_pass http://127.0.0.1:9090/Videos/;
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass_request_headers on;

        add_header Content-Type video/mp4;
    }
}
```

And the `s3proxy.conf` file:

```
s3proxy.authorization=none
s3proxy.endpoint=http://127.0.0.1:9090
jclouds.provider=filesystem
jclouds.identity=
jclouds.credential=
jclouds.filesystem.basedir=/home/ivan
```

On the client side (chrome browser) the only thing that happens is that the video doesn't play. On the server side I saw the previous trace trying to debug the code from intellij.

If I start `s3proxy` in debug mode, this is the log:

```
ivan@nobita ~ $ java -DLOG_LEVEL=trace -jar s3proxy --properties s3proxy.conf 
I 06-17 07:22:52.828 main org.eclipse.jetty.util.log:186 |::] Logging initialized @1034ms
I 06-17 07:22:52.852 main o.eclipse.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
I 06-17 07:22:52.875 main o.e.j.server.ServerConnector:266 |::] Started ServerConnector@6859c52e{HTTP/1.1}{127.0.0.1:9090}
I 06-17 07:22:52.875 main o.eclipse.jetty.server.Server:379 |::] Started @1082ms
D 06-17 07:22:55.295 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:214 |::] request: (GET /Videos/6015_2018_2035.h264.cutted.mp4)@43817993 org.eclipse.jetty.server.Request@29c9c09
T 06-17 07:22:55.295 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cookie: auth=Z3Vlc3Q6Z3Vlc3Q%3D; JSESSIONID=41190A94E3F158EA1CAD1C923333ED81; org.cups.sid=826d95510a441e7461f33f181ee1a478; GUID=0kLgYcjo2dZEn0gnwg5b; m=34e2:|47ba:t|18c3:t|3a8e:chart|54ae:small|29ac:60%7C5|ca3:t|4e99:t|77cb:t|2a03:t
T 06-17 07:22:55.295 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: If-Range: Wed, 17 Jun 2015 05:09:59 GMT
T 06-17 07:22:55.295 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cache-Control: max-age=0
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Connection: close
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Host: localhost
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Encoding: gzip, deflate, sdch
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Language: en-US,en;q=0.8,es;q=0.6
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Range: bytes=524058-524058
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Real-IP: 127.0.0.1
T 06-17 07:22:55.296 qtp182670350-13 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Scheme: http
D 06-17 07:22:55.298 qtp182670350-13 o.j.b.config.LocalBlobStore:56 |::] Retrieving blob with key 6015_2018_2035.h264.cutted.mp4 from container Videos
D 06-17 07:22:55.298 qtp182670350-13 o.j.b.config.LocalBlobStore:56 |::] Opening blob in container: Videos - 6015_2018_2035.h264.cutted.mp4
D 06-17 07:22:55.401 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:214 |::] request: (GET /Videos/6015_2018_2035.h264.cutted.mp4)@629598206 org.eclipse.jetty.server.Request@2586e7fe
T 06-17 07:22:55.401 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cookie: auth=Z3Vlc3Q6Z3Vlc3Q%3D; JSESSIONID=41190A94E3F158EA1CAD1C923333ED81; org.cups.sid=826d95510a441e7461f33f181ee1a478; GUID=0kLgYcjo2dZEn0gnwg5b; m=34e2:|47ba:t|18c3:t|3a8e:chart|54ae:small|29ac:60%7C5|ca3:t|4e99:t|77cb:t|2a03:t
T 06-17 07:22:55.401 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cache-Control: max-age=0
T 06-17 07:22:55.401 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
T 06-17 07:22:55.401 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Connection: close
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Host: localhost
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Encoding: gzip, deflate, sdch
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Language: en-US,en;q=0.8,es;q=0.6
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Real-IP: 127.0.0.1
T 06-17 07:22:55.402 qtp182670350-16 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Scheme: http
D 06-17 07:22:55.402 qtp182670350-16 o.j.b.config.LocalBlobStore:56 |::] Retrieving blob with key 6015_2018_2035.h264.cutted.mp4 from container Videos
D 06-17 07:22:55.402 qtp182670350-16 o.j.b.config.LocalBlobStore:56 |::] Opening blob in container: Videos - 6015_2018_2035.h264.cutted.mp4
D 06-17 07:22:55.667 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:214 |::] request: (GET /Videos/6015_2018_2035.h264.cutted.mp4)@417954387 org.eclipse.jetty.server.Request@18e97a53
T 06-17 07:22:55.667 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cookie: auth=Z3Vlc3Q6Z3Vlc3Q%3D; JSESSIONID=41190A94E3F158EA1CAD1C923333ED81; org.cups.sid=826d95510a441e7461f33f181ee1a478; GUID=0kLgYcjo2dZEn0gnwg5b; m=34e2:|47ba:t|18c3:t|3a8e:chart|54ae:small|29ac:60%7C5|ca3:t|4e99:t|77cb:t|2a03:t
T 06-17 07:22:55.667 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Cache-Control: max-age=0
T 06-17 07:22:55.667 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept: */*
T 06-17 07:22:55.667 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Connection: close
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Referer: http://localhost/6015_2018_2035.h264.cutted.mp4
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Host: localhost
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Encoding: identity;q=1, *;q=0
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Accept-Language: en-US,en;q=0.8,es;q=0.6
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: Range: bytes=0-
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Real-IP: 127.0.0.1
T 06-17 07:22:55.668 qtp182670350-17 o.gaul.s3proxy.S3ProxyHandler:231 |::] header: X-Scheme: http
D 06-17 07:22:55.669 qtp182670350-17 o.j.b.config.LocalBlobStore:56 |::] Retrieving blob with key 6015_2018_2035.h264.cutted.mp4 from container Videos
D 06-17 07:22:55.669 qtp182670350-17 o.j.b.config.LocalBlobStore:56 |::] Opening blob in container: Videos - 6015_2018_2035.h264.cutted.mp4
```

No exception is thrown but the video doesn't start in chrome.

If I execute a curl against the nginx: `http://localhost/6015_2018_2035.h264.cutted.mp4` I get the raw data. With curl works (at least I get the raw data).
The problem is how the browser works when trying to play a video from its embedded browser, so it's not possible to test it with curl (at least I don't know how to do this "two-calls-behaviour).

Now you can see different screenshots first using s3proxy and then using other method to serve the videos (gulp):

**s3proxy**

1st call

![s3proxy_1](https://cloud.githubusercontent.com/assets/559192/8200496/255361d2-14c6-11e5-92e4-f046608f7edd.png)

2nd call

![s3proxy_2](https://cloud.githubusercontent.com/assets/559192/8200498/28862c86-14c6-11e5-9fff-222d7446c0d0.png)

And there are no more calls

**gulp**

1st call

![direct_1](https://cloud.githubusercontent.com/assets/559192/8200518/55976d34-14c6-11e5-99a0-5aeabbf48520.png)

2nd call
![direct_2](https://cloud.githubusercontent.com/assets/559192/8200520/57e6e024-14c6-11e5-9d22-18beba119801.png)

3rd call
![direct_3](https://cloud.githubusercontent.com/assets/559192/8200522/5a01b5dc-14c6-11e5-8984-a10550c9fe7a.png)

4th call
![direct_4](https://cloud.githubusercontent.com/assets/559192/8200523/5c46689c-14c6-11e5-9e94-8d81858a37df.png)

Nth call
And the video starts playing.

Thank you very much for your time.

**Comment by lmivan** [comment]
So If you compare the different screenshot it seems that the only missing thing is that s3proxy doesn't add the `Content-Range` header.

I've been doing another test. I hardcoded the `Content-Range` header in my nginx configuration just adding this:

```
add_header Content-Range "bytes 0-54704541/54704542";
```

And now the browser sends a 3rd request to get more pieces of the video. Of course it doesn't start to play it because the bytes in every response should be different, but I think with that header everything should work.

**Comment by andrewgaul** [comment]
@lmivan I verified your symptoms and added additional tests at ceph/s3-tests#61.  I will add this functionality to S3Proxy later today.  Thank you for your help diagnosing this!

**Comment by lmivan** [comment]
Great, thank you very much. Looking forward to testing the new code :-)

Thank you very much!

**Comment by andrewgaul** [comment]
@lmivan Fixed in master although the filesystem blobstore has a dependency on jclouds/jclouds#776 which will wind up in the upstream snapshot repository over the next day.

I am curious about your use case for S3Proxy -- it should preserve metadata like Content-Type (except for the filesystem blobstore on Mac OS X due to [JDK-8030048](https://bugs.openjdk.java.net/browse/JDK-8030048)) without nginx.  Can you expand on any other problems you are having?

**Comment by lmivan** [comment]
@andrewgaul Thank you. I'll wait until the jclouds dependency gets updated in the snapshot repository.

In using Linux but I've checked that s3proxy doesn't return the `Content-Type` of the file (at least for a video). That's why I used nginx to set the header. Should I open another issue related to the Content-Type? It should be great if s3proxy returns it correctly because we plan to server not only videos but images and other files such as documents, pdf,...

And about my use case, we want to serve this videos (and the images) in a RESTful API to the frontend. The problem is that we do not want the final user be able to copy the url of a video and send it by email to anyone. So, what we're going to do is expose a local filesystem using s3proxy and use the Amazon S3 signed urls to generate urls to access those files and videos that will expire after a short period of time.

That sounds good for your?

**Comment by lmivan** [comment]
Hi @andrewgaul.

It seems that the snapshot repository for jcloud is not updated so what I've done is just clone the jclouds repository and generate the updated version.

With your last changes it is still not working. I've submitted this PR https://github.com/jclouds/jclouds/pull/779 to fix the Content-Range header.

Besides that change I still need to do the following configuration in my nginx file:

```
    add_header Accept-Ranges bytes;
    add_header Content-Type video/mp4;
```

Now I can reproduce the video using the Chrome embedded browser using nginx in front of s3proxy. So I think that S3proxy should add those headers.

Should I open a new issue?

**Comment by lmivan** [comment]
I've been doing more tests and it seems that the header `Accept-Ranges` is not really necessary (although I think it should be added).

The `Content-Type` header is mandatory because without it the video is downloaded instead of being played in the embedded browser.

**Comment by andrewgaul** [comment]
I need to read up some more on the HTTP spec to understand the `Accept-Ranges` header.  Let's address that within this issue.

Usually clients set the `Content-Type` during blob creation but since you are exposing existing files via the filesystem blobstore they have no headers set.  We could automatically detect the Content-Type in the jclouds filesystem blobstore similar to how OpenStack Swift uses the file extension to map to MIME type with the `X-Detect-Content-Type` header.  Can you open an upstream JIRA issue for this here:

https://issues.apache.org/jira/browse/JCLOUDS

**Comment by lmivan** [comment]
Issue created: https://issues.apache.org/jira/browse/JCLOUDS-941

Thank you very much!

**Comment by kinoute** [comment]
We have a similar issue where S3proxy works perfectly to serve images but is unable to serve mp4 files and let the browser play them. Downloading the mp4 works fine.

We can see two requests: the original one which seems to download the whole file and another one that asks for a range bytes of 0-1, returning a 206 partial content status code.

Funny enough, the video can be played on Firefox. But not on Chrome/chromium, Safari & Edge. It doesn't load.

Is there any tips to allow serving mp4 files in the browser? We also try to use a nginx on front of S3Proxy to add more headers but we were not successful unless we hardcode the `Content-Range` header as @ilopmar tried.

**Comment by kinoute** [comment]
In our case, adding these lines to our nginx fixed the issue:

```nginx
add_header Accept-Ranges bytes;
add_header Content-Type video/mp4;

proxy_set_header   Range $slice_range;
proxy_set_header   Content-Range $slice_range;
```
